# Configuration pour cluster kind avec mapping de ports
# Permet d'exposer le NodePort 31200 vers l'extérieur
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31200
        hostPort: 31200
        protocol: TCP